# Generated by Django 5.2.6 on 2025-12-29 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventures', '0002_initial_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_number', models.IntegerField(default=1)),
                ('puzzle_data', models.TextField()),
                ('solution_data', models.TextField()),
                ('seed', models.CharField(max_length=100)),
                ('difficulty_score', models.FloatField(default=0.0)),
                ('times_solved', models.IntegerField(default=0)),
                ('average_solve_time', models.FloatField(default=0.0)),
                ('min_solve_time', models.FloatField(default=0.0)),
                ('max_solve_time', models.FloatField(default=0.0)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['venture_game', 'puzzle_number'],
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_type', models.CharField(max_length=50)),
                ('hint_data', models.JSONField()),
                ('cost', models.IntegerField(default=10)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='gaming.puzzle')),
            ],
            options={
                'ordering': ['cost'],
            },
        ),
        migrations.CreateModel(
            name='VentureGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('sudoku', 'Sudoku'), ('kakuro', 'Kakuro'), ('cryptogram', 'Cryptogram')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='medium', max_length=20)),
                ('grid_size', models.IntegerField(default=10)),
                ('auto_generate', models.BooleanField(default=True)),
                ('generation_algorithm', models.CharField(default='backtracking', max_length=50)),
                ('base_points', models.IntegerField(default=100)),
                ('time_bonus', models.BooleanField(default=True)),
                ('time_limit_seconds', models.IntegerField(default=3600)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='ventures.venture')),
            ],
            options={
                'ordering': ['game_type'],
                'unique_together': {('venture', 'game_type')},
            },
        ),
        migrations.AddField(
            model_name='puzzle',
            name='venture_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='gaming.venturegame'),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('top_scores', models.JSONField(default=list)),
                ('venture_game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='gaming.venturegame')),
            ],
            options={
                'ordering': ['venture_game'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='puzzle',
            unique_together={('venture_game', 'puzzle_number')},
        ),
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_state', models.JSONField(default=dict)),
                ('moves_history', models.JSONField(default=list)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('hints_used', models.IntegerField(default=0)),
                ('errors_made', models.IntegerField(default=0)),
                ('time_spent_seconds', models.FloatField(default=0.0)),
                ('base_score', models.IntegerField(default=0)),
                ('time_bonus', models.IntegerField(default=0)),
                ('penalty_points', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gaming.puzzle')),
                ('venture_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gaming.venturegame')),
            ],
            options={
                'ordering': ['-start_time'],
                'unique_together': {('player', 'puzzle')},
            },
        ),
    ]
