# Generated by Django 5.2.6 on 2025-12-29 04:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('funding_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_tickets', models.IntegerField(default=100)),
                ('tickets_sold', models.IntegerField(default=0)),
                ('nft_contract_address', models.CharField(blank=True, max_length=100)),
                ('nft_base_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funding_start', models.DateTimeField()),
                ('funding_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('funding', 'Funding'), ('funded', 'Funded'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VentureTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nft_token_id', models.CharField(blank=True, max_length=100)),
                ('nft_metadata', models.JSONField(blank=True, default=dict)),
                ('purchase_hash', models.CharField(blank=True, max_length=200)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('purchased', 'Purchased'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venture_tickets', to=settings.AUTH_USER_MODEL)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ventures.venture')),
            ],
            options={
                'ordering': ['ticket_number'],
                'unique_together': {('venture', 'ticket_number')},
            },
        ),
        migrations.CreateModel(
            name='VentureOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venture_ownerships', to=settings.AUTH_USER_MODEL)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='ventures.venture')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='ventures.ventureticket')),
            ],
            options={
                'unique_together': {('venture', 'owner')},
            },
        ),
    ]
