# Generated by Django 5.2.6 on 2025-12-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venture',
            name='funding_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venture',
            name='funding_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
