# Generated by Django 5.2.6 on 2025-12-27 08:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='CEO Matrix Challenge', max_length=200)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('genius', 'Genius Only')], default='medium', max_length=50)),
                ('rows', models.IntegerField(default=5)),
                ('cols', models.IntegerField(default=5)),
                ('layers', models.IntegerField(default=3)),
                ('categories', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('matrix_data', models.JSONField(default=dict)),
                ('solution_path', models.JSONField(default=list)),
                ('max_moves', models.IntegerField(default=100)),
                ('total_players', models.IntegerField(default=0)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('solved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solved_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerGameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_position', models.JSONField(default=dict)),
                ('moves_made', models.IntegerField(default=0)),
                ('cells_visited', models.JSONField(default=list)),
                ('player_path', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_move_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_winner', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('efficiency', models.FloatField(default=0.0)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='matrix.matrixgame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('player', 'game')},
            },
        ),
        migrations.CreateModel(
            name='MatrixLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('moves', models.IntegerField(default=0)),
                ('time_taken', models.DurationField()),
                ('solved_at', models.DateTimeField()),
                ('rank', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='matrix.matrixgame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_scores', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to='matrix.playergamesession')),
            ],
            options={
                'ordering': ['-score', 'time_taken', 'moves'],
            },
        ),
    ]
